project:
  type: manuscript
  preview: 
    port: 4002

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true

  # (other formats)
  # pdf: default
  typst: default
  # agu-pdf: default

execute:
  freeze: true

code-links: 
  - repo
  - href: https://app.tana.inc?nodeid=Kmdzbyj-36NM
    text: Tana

citation:
  container-title: "JGR: Space Physics"

keep-tex: true