project:
  type: website
  preview:
    port: 4002

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Manuscript"
        href: _manuscript/index.html
      - text: "Notes"
        href: notes.qmd
      - sidebar:notebooks
      - text: "Presentations"
        menu: 
          - href: presentations/grpMeeting_Zijin_2024-09.qmd
            text: Group Meeting 2024 Sep 8
          - href: presentations/AGU23_poster.qmd
            text: AGU23 Poster
          - href: presentations/SPARTHRB_Zijin_202310.pptx
            text: SPARTHRB 2023 Fall
    tools:
      - icon: github
        href: https://github.com/Beforerr/ids_spatial_evolution_juno
  sidebar:
    - id: notebooks
      title: Notebooks
      contents: "notebooks/**"

format:
  html: 
    lightbox: auto
    toc: true
    code-fold: true

bibliography:
  - files/bibexport.bib
  - ../share/bibliography/research.bib

wrap: preserve