project:
  type: manuscript
  preview:
    port: 4002

manuscript:
  article: index.qmd
  resources:
    - presentations/AGU23_poster.pdf

format:
  html:
    comments:
      hypothesis: true
  agu-pdf:
    cite-method: natbib # biblatex is not supported
    keep-tex: true
    bibliography:
      - files/bibliography/full_anton.bib
      - files/bibliography/addon_anton.bib

execute:
  freeze: true

citation:
  container-title: "JGR: Space Physics"

bibliography:
  - files/bibexport.bib
  - ../research.bib

wrap: preserve