project:
  type: manuscript
  render: 
    - "!*.qmd"
    - "!presentations/"

manuscript:
  article: article.qmd # Current can not be put in a subdirectory

format:
  html:
    comments:
      hypothesis: true
  agu-pdf:
    cite-method: natbib # biblatex is not supported
    keep-tex: true
    bibliography:
      - files/bibliography/full_anton.bib
      - files/bibliography/addon_anton.bib

citation:
  container-title: "JGR: Space Physics"