project:
  type: manuscript
  render:
    - "article.qmd"

manuscript:
  article: article.qmd

format:
  html:
    comments:
      hypothesis: true
  agu-pdf:
    cite-method: natbib # biblatex is not supported
    keep-tex: true
    latex-clean: false
    bibliography:
      - files/bibliography/full_anton.bib
      - files/bibliography/addon_anton.bib
    # lof: true
    # lot: true

citation:
  container-title: "JGR: Space Physics"
