project:
  type: manuscript
  preview: 
    port: 4002

manuscript:
  article: index.qmd
  resources: 
    - presentations/AGU23_poster.pdf

format:
  html:
    comments:
      hypothesis: true

  # (other formats)
  # pdf: default
  # typst: default
  # agu-pdf: default

execute:
  freeze: true

citation:
  container-title: "JGR: Space Physics"