name: juno
dependencies:
  - python<3.11
  - jupyter

  - intake
  - polars
  - xarray

  - pydantic
  
  - grpcio # used in `modin`, using conda for (Apple Silicon) Support

  - pytables # used in `pyspedas`
  - pip
  - pip:
    - pyspedas
    # - ../space_analysis
    # - ../ids_finder
    # - ../beforerr_dev