[project]
name = "juno"
version = "0.1.0"
description = "Add a short description here"
authors = ["Beforerr <zzj956959688@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "<3.11"
jupyter = "*"
intake = "*"
polars = "*"
xarray = "*"
pydantic = "*"
pytables = "*"
scipy = "*"

[pypi-dependencies]
pyspedas = "*"
great_tables = "*"
discontinuitypy = { path = "../ids_finder", editable = true}
Beforerr = { path = "../beforerr_dev", editable = true}