[project]
name = "juno"
version = "0.1.0"
description = "Utilities for working with Juno data"
authors = [{ name = "Beforerr", email = "zzj956959688@gmail.com" }]
requires-python = ">= 3.10, < 3.12"
dependencies = [
    "speasy",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
jupyter = "*"
intake = "*"
polars = "*"
xarray = "*"
pydantic = "*"
scipy = "*"

[tool.pixi.pypi-dependencies]
juno = { path = ".", editable = true }
great_tables = "*"
beforerr = { path = "../../src/beforerr_dev", editable = true }
pooch = "*"
pdr = "*"
discontinuitypy = { path = "../discontinuitypy", editable = true }
space_analysis = { path = "../../src/space-analysis.py", editable = true }